seed_everything: 42

device: cuda

pl_module:
  _target_: ptls.frames.coles.CoLESModule
  validation_metric:
    _target_: ptls.frames.coles.metric.BatchRecallTopK
    K: 4
    metric: cosine
  seq_encoder:
    _target_: ptls.nn.RnnSeqEncoder
    trx_encoder: 
      _target_: ptls.nn.TrxEncoder
      norm_embeddings: false
      embeddings_noise: 0.003
      embeddings: 
        currency: 
          in: 13
          out: 2
        operation_kind: 
          in: 9
          out: 2
        card_type: 
          in: 177
          out: 2
        operation_type: 
          in: 24
          out: 2
        operation_type_group: 
          in: 6
          out: 2
        ecommerce_flag: 
          in: 5
          out: 1
        payment_system: 
          in: 9
          out: 2
        income_flag: 
          in: 5
          out: 1
        mcc: 
          in: 110
          out: 16
        country: 
          in: 26
          out: 1
        city: 
          in: 163
          out: 1
        mcc_category: 
          in: 30
          out: 16
        day_of_week: 
          in: 9
          out: 2
        hour: 
          in: 25
          out: 2
        weekofyear: 
          in: 55
          out: 2
      numeric_values: 
        amnt: identity
        hour_diff: log
    type: gru
    hidden_size: 1024
    bidir: false
    trainable_starter: static
  head:
    _target_: ptls.nn.Head
    use_norm_encoder: true
    input_size: ${pl_module.seq_encoder.hidden_size}
  loss:
    _target_: ptls.frames.coles.losses.ContrastiveLoss
    margin: 0.5
    sampling_strategy:
      _target_: ptls.frames.coles.sampling_strategies.HardNegativePairSelector
      neg_count: 5
  optimizer_partial:
    _partial_: true
    _target_: torch.optim.Adam
    lr: 0.002
    weight_decay: 0.0

random_model: true

inference_dataloader: 
  col_id: app_id
  dataset_files: 
    - ${hydra:runtime.cwd}/data/train_trx.parquet
    - ${hydra:runtime.cwd}/data/test_trx.parquet
  SeqLenLimit: 
    max_seq_len: 1600
  loader: 
    num_workers: 8
    batch_size: 1000
  torch_multiprocessing_sharing_strategy: file_system

output: 
  path: ${hydra:runtime.cwd}/data/random_embeddings
  format: pickle
