defaults:
  - _self_
  - inference_dataloader/default
  - output/pickle

seed_everything: 42
embed_file_name: agg_feat_embed

pl_module_inference:
  _target_: ptls.frames.coles.CoLESModule
  seq_encoder:
    _target_: ptls.nn.AggFeatureSeqEncoder
    embeddings:
      mcc_code:
        in: 200
      tr_type:
        in: 100
    numeric_values:
      amount: identity
    was_logified: true
    log_scale_factor: 1
