defaults:
  - _self_
  - pl_module_inference/seq_to_target
  - inference_dataloader/default
  - output/pickle

seed_everything: 42
logger_name: cpc_model
model_path: models/cpc_model.p
embed_file_name: cpc_embeddings

data_module:
  _target_: ptls.data_load.data_module.cpc_data_module.CpcDataModuleTrain
  type: map
  setup: 
    col_id: customer_id
    dataset_files: 
      data_path: ${hydra:runtime.cwd}/data/train_trx.parquet
    split_by: files
    valid_size: 0.05
    valid_split_seed: 42
  train: 
    min_seq_len: 25
    split_strategy: 
      split_strategy: SampleSlices
      split_count: 5
      cnt_min: 15
      cnt_max: 75
    trx_dropout: 0.01
    num_workers: 8
    batch_size: 64
    augmentations: 
      - 
        - DropoutTrx
        - 
          trx_dropout: 0.01
      - 
        - SeqLenLimit
        - 
          max_seq_len: 1200
  valid: 
    split_strategy: 
      split_strategy: SampleSlices
      split_count: 5
      cnt_min: 25
      cnt_max: 100
    num_workers: 16
    batch_size: 64
    augmentations: 
      - 
        - SeqLenLimit
        - 
          max_seq_len: 1200

trainer: 
  gpus: 1
  auto_select_gpus: false
  max_epochs: 30
  enable_checkpointing: false
  deterministic: true

pl_module:
  _target_: ptls.frames.cpc.CpcModule
  seq_encoder:
    _target_: ptls.nn.RnnSeqEncoder
    trx_encoder: 
      _target_: ptls.nn.TrxEncoder
      norm_embeddings: false
      embeddings_noise: 0.003
      embeddings: 
        mcc_code: 
          in: 200
          out: 128
        tr_type: 
          in: 100
          out: 127
      numeric_values: 
        amount: identity
    type: gru
    hidden_size: 256
    bidir: false
    trainable_starter: static
  n_forward_steps: 6
  n_negatives: 40
  lr_scheduler_partial:
    _partial_: true
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 5
    gamma: 0.5
  optimizer_partial:
    _partial_: true
    _target_: torch.optim.Adam
    lr: 0.001
    weight_decay: 0.0
