defaults:
  - _self_
  - pl_module/defaults

seed_everything: 42
logger_name: cpc_finetuning
pretrained_encoder_path: models/cpc_model.p

data_module:
  _target_: ptls.data_load.data_module.cls_data_module.ClsDataModuleTrain
  type: map
  setup: 
    dataset_files: 
      train_data_path: ${hydra:runtime.cwd}/data/train_trx.parquet
      test_data_path: ${hydra:runtime.cwd}/data/test_trx.parquet
    col_id: customer_id
    col_id_dtype: int
    col_target: gender
    split_by: embeddings_validation
    fold_info: ${hydra:runtime.cwd}/conf/embeddings_validation.work/folds/folds.json
  train: 
    min_seq_len: 0
    augmentations: 
      - 
        - RandomSlice
        - 
          min_len: 250
          max_len: 350
          rate_for_min: 0.9
      - 
        - DropoutTrx
        - 
          trx_dropout: 0.01
    num_workers: 16
    batch_size: 32
  valid: 
    augmentations: 
      - 
        - SeqLenLimit
        - 
          max_seq_len: 1200
    num_workers: 8
    batch_size: 64

embedding_validation_results: 
  model_name: nn
  feature_name: cpc_finetuning
  output_path: ${hydra:runtime.cwd}/results/cpc_finetuning_results.json

trainer: 
  gpus: 1
  auto_select_gpus: false
  max_epochs: 5
  log_every_n_steps: 10
  enable_checkpointing: false
  deterministic: true

pl_module:
  _target_: ptls.frames.supervised.SequenceToTarget
  seq_encoder:
    _target_: torch.load
    f: ${pretrained_encoder_path}
  pretrained_lr: 0.0001
  head:
    input_size: 256
